### ISSUE TITLE
function "onDeepLinking" is not triggered when app is terminated on IOS

### ISSUE THREAD

**Issue by scriabinEtude** [AppsFlyerSDK/appsflyer-flutter-plugin#291]
**Describe the bug**
function `onDeepLinking` is not triggered when app is terminated on IOS

**To Reproduce**
1. install app. and run
2. terminate app
3. click onelink
4. app is launched
5.`onDeepLinking` isn't called.

**Expected behavior**
`onDeepLinking` is triggered with `deep_link_value`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac M2 Ventura 13.4.1 (c)(22F770820d
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: IOS 16.6
 - Browser: Chrome, Google, Safari

## Additional context
appsflyer_sdk: ^6.11.3
I'm using `firebase_dynamic_links: ^5.2.0`,  `app_links: ^3.4.3` to handle other links. 
so `FlutterDeepLinkingEnabled` is `false`

```dart
// my code

var _sdk = AppsflyerSdk(options).initSdk(
  registerConversionDataCallback: true,
  registerOnAppOpenAttributionCallback: true,
  registerOnDeepLinkingCallback: true,
);


listen() {
  _sdk.onAppOpenAttribution((res) {
    print("onAppOpenAttribution res: $res");
  });
  _sdk.onInstallConversionData((res) {
    print("onInstallConversionData res: $res");
  });
  _sdk.onDeepLinking((DeepLinkResult dp) {
    switch (dp.status) {
      case Status.FOUND:
        print(dp.deepLink?.toString());
        print("deep link value: ${dp.deepLink?.deepLinkValue}");
        break;
      case Status.NOT_FOUND:
        print("deep link not found");
        break;
      case Status.ERROR:
        print("deep link error: ${dp.error}");
        break;
      case Status.PARSE_ERROR:
        print("deep link status parsing error");
        break;
    }
    print("onDeepLinking res: $dp");
    GotoPath.shared.fromEncodedUrl(dp.deepLink?.deepLinkValue);
  });
}
```

function `onDeepLinking` doing well under the state that app is running.
but when app is terminated, it doesn't.
i want to use onelink and other links together.

thanks

**Comment by kalyanchandra48** [comment]
@scriabinEtude 
Did you get a Solution for this Issue or any support?

**Comment by chooyan-eng** [comment]
@scriabinEtude I was in the same situation and solved by calling `.initSdk()` AFTER `_sdk.onDeepLinking()`. 

Readme says "onDeepLinking must be made prior to the initialization code of the SDK". 

https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/doc/DeepLink.md

**Comment by zakton5** [comment]
@chooyan-eng I applied to fix you mentioned but I still have the same problem. `onDeepLinking` does not fire when the app is terminated.

**Comment by JeisonSanches** [comment]
I'm facing this same problem. Any updates?
