### ISSUE TITLE
When building, I get the error "cannot access XXXX".

### ISSUE THREAD

**Issue by sumichell** [AppsFlyerSDK/appsflyer-flutter-plugin#339]
When building, I get the error "cannot access XXXX".
As of September 2nd, it was successful, but now when I build the same code, an error occurs.
I have changed the flutter_appsflyer_sdk to the latest 6.15.1 and still have the same issue.

```
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:12: error: cannot access AFAdRevenueData
import com.appsflyer.AFAdRevenueData;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AFAdRevenueData.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:13: error: cannot access AFLogger
import com.appsflyer.AFLogger;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AFLogger.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:14: error: cannot access AppsFlyerConsent
import com.appsflyer.AppsFlyerConsent;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AppsFlyerConsent.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:15: error: cannot access AppsFlyerConversionListener
import com.appsflyer.AppsFlyerConversionListener;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AppsFlyerConversionListener.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:16: error: cannot access AppsFlyerInAppPurchaseValidatorListener
import com.appsflyer.AppsFlyerInAppPurchaseValidatorListener;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AppsFlyerInAppPurchaseValidatorListener.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:17: error: cannot access AppsFlyerLib
import com.appsflyer.AppsFlyerLib;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AppsFlyerLib.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:18: error: cannot access AppsFlyerProperties
import com.appsflyer.AppsFlyerProperties;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/AppsFlyerProperties.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:19: error: cannot access MediationNetwork
import com.appsflyer.MediationNetwork;
                    ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/MediationNetwork.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:20: error: cannot access DeepLinkListener
import com.appsflyer.deeplink.DeepLinkListener;
                             ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/deeplink/DeepLinkListener.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:21: error: cannot access DeepLinkResult
import com.appsflyer.deeplink.DeepLinkResult;
                             ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/deeplink/DeepLinkResult.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:22: error: cannot access CrossPromotionHelper
import com.appsflyer.share.CrossPromotionHelper;
                          ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/share/CrossPromotionHelper.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:23: error: cannot access LinkGenerator
import com.appsflyer.share.LinkGenerator;
                          ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/share/LinkGenerator.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:24: error: cannot access ShareInviteHelper
import com.appsflyer.share.ShareInviteHelper;
                          ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/share/ShareInviteHelper.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:25: error: cannot access Plugin
import com.appsflyer.internal.platform_extension.Plugin;
                                                ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/internal/platform_extension/Plugin.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:26: error: cannot access PluginInfo
import com.appsflyer.internal.platform_extension.PluginInfo;
                                                ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/internal/platform_extension/PluginInfo.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:27: error: cannot access AppsFlyerRequestListener
import com.appsflyer.attribution.AppsFlyerRequestListener;
                                ^
  bad class file: /Users/vagrant/.gradle/caches/transforms-3/e2fd19dbe1032c0ad7c416842c8161e6/transformed/jetified-af-android-sdk-6.15.1-api.jar(/com/appsflyer/attribution/AppsFlyerRequestListener.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:64: error: cannot find symbol
    private static DeepLinkResult cachedDeepLinkResult;
                   ^
  symbol:   class DeepLinkResult
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:94: error: cannot find symbol
    private final AppsFlyerConversionListener afConversionListener = new AppsFlyerConversionListener() {
                  ^
  symbol:   class AppsFlyerConversionListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:144: error: cannot find symbol
    private final DeepLinkListener afDeepLinkListener = new DeepLinkListener() {
                  ^
  symbol:   class DeepLinkListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:94: error: cannot find symbol
    private final AppsFlyerConversionListener afConversionListener = new AppsFlyerConversionListener() {
                                                                         ^
  symbol:   class AppsFlyerConversionListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:95: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:107: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:119: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:132: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:144: error: cannot find symbol
    private final DeepLinkListener afDeepLinkListener = new DeepLinkListener() {
                                                            ^
  symbol:   class DeepLinkListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:147: error: cannot find symbol
        public void onDeepLinking(DeepLinkResult deepLinkResult) {
                                  ^
  symbol: class DeepLinkResult
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:146: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:362: error: cannot find symbol
                AppsFlyerLib.getInstance().performOnDeepLinking(intent, mApplication);
                ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:376: error: cannot find symbol
        AppsFlyerLib.getInstance().anonymizeUser(shouldAnonymize);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:382: error: cannot find symbol
            final AppsFlyerLib instance = AppsFlyerLib.getInstance();
                  ^
  symbol:   class AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:382: error: cannot find symbol
            final AppsFlyerLib instance = AppsFlyerLib.getInstance();
                                          ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:383: error: cannot find symbol
            instance.start(activity, null, new AppsFlyerRequestListener() {
                                               ^
  symbol:   class AppsFlyerRequestListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:384: error: method does not override or implement a method from a supertype
                @Override
                ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:394: error: method does not override or implement a method from a supertype
                @Override
                ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:418: error: cannot find symbol
        final AppsFlyerLib instance = AppsFlyerLib.getInstance();
              ^
  symbol:   class AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:418: error: cannot find symbol
        final AppsFlyerLib instance = AppsFlyerLib.getInstance();
                                      ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:431: error: cannot find symbol
        AppsFlyerConsent consentData;
        ^
  symbol:   class AppsFlyerConsent
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:433: error: cannot find symbol
            consentData = AppsFlyerConsent.forGDPRUser(hasConsentForDataUsage, hasConsentForAdsPersonalization);
                          ^
  symbol:   variable AppsFlyerConsent
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:435: error: cannot find symbol
            consentData = AppsFlyerConsent.forNonGDPRUser();
                          ^
  symbol:   variable AppsFlyerConsent
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:438: error: cannot find symbol
        AppsFlyerLib.getInstance().setConsentData(consentData);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:446: error: cannot find symbol
        AppsFlyerLib.getInstance().enableTCFDataCollection(shouldCollect);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:454: error: cannot find symbol
            AppsFlyerLib.getInstance().addPushNotificationDeepLinkPath(depplinkPathArr);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:461: error: cannot find symbol
        AppsFlyerLib.getInstance().setDisableNetworkData(disableNetworkData);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:466: error: cannot find symbol
        result.success(AppsFlyerLib.getInstance().getOutOfStore(this.mContext));
                       ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:472: error: cannot find symbol
            AppsFlyerLib.getInstance().setOutOfStore(sourceName);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:480: error: cannot find symbol
        AppsFlyerLib.getInstance().setResolveDeepLinkURLs(urlsArr);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:489: error: cannot find symbol
            AppsFlyerLib.getInstance().setPartnerData(partnerId, partnerData);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:498: error: cannot find symbol
            AppsFlyerLib.getInstance().setSharingFilterForPartners(partners);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:506: error: cannot find symbol
            AppsFlyerLib.getInstance().setDisableAdvertisingIdentifiers(true);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:508: error: cannot find symbol
            AppsFlyerLib.getInstance().setDisableAdvertisingIdentifiers(false);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:517: error: cannot find symbol
            AppsFlyerLib.getInstance().enableFacebookDeferredApplinks(true);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:519: error: cannot find symbol
            AppsFlyerLib.getInstance().enableFacebookDeferredApplinks(false);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:525: error: cannot find symbol
        AppsFlyerLib.getInstance().sendPushNotificationData(activity);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:551: error: cannot find symbol
                AppsFlyerLib.getInstance().sendPushNotificationData(activity);
                ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:581: error: cannot find symbol
        AppsFlyerLib.getInstance().setOneLinkCustomDomain(brandDomainsArray);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:591: error: cannot find symbol
            CrossPromotionHelper.logAndOpenStore(mContext, appId, campaign, data);
            ^
  symbol:   variable CrossPromotionHelper
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:602: error: cannot find symbol
            CrossPromotionHelper.logCrossPromoteImpression(mContext, appId, campaign, data);
            ^
  symbol:   variable CrossPromotionHelper
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:612: error: cannot find symbol
            AppsFlyerLib.getInstance().setAppInviteOneLink(oneLinkId);
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:630: error: cannot find symbol
        LinkGenerator linkGenerator = ShareInviteHelper.generateInviteUrl(mContext);
        ^
  symbol:   class LinkGenerator
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:630: error: cannot find symbol
        LinkGenerator linkGenerator = ShareInviteHelper.generateInviteUrl(mContext);
                                      ^
  symbol:   variable ShareInviteHelper
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:656: error: package LinkGenerator does not exist
        LinkGenerator.ResponseListener listener = new LinkGenerator.ResponseListener() {
                     ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:656: error: package LinkGenerator does not exist
        LinkGenerator.ResponseListener listener = new LinkGenerator.ResponseListener() {
                                                                   ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:659: error: method does not override or implement a method from a supertype
            @Override
            ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:671: error: method does not override or implement a method from a supertype
            @Override
            ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:700: error: cannot find symbol
                                DeepLinkResult dp = (DeepLinkResult) data;
                                ^
  symbol: class DeepLinkResult
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:700: error: cannot find symbol
                                DeepLinkResult dp = (DeepLinkResult) data;
                                                     ^
  symbol: class DeepLinkResult
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:705: error: package DeepLinkResult does not exist
                                if (dp.getStatus() == DeepLinkResult.Status.FOUND) {
                                                                    ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:723: error: cannot find symbol
        AppsFlyerLib.getInstance().setSharingFilterForAllPartners();
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:728: error: cannot find symbol
        AppsFlyerLib.getInstance().setSharingFilter();
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:733: error: cannot find symbol
        result.success(AppsFlyerLib.getInstance().getAppsFlyerUID(this.mContext));
                       ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:744: error: cannot find symbol
        AppsFlyerLib.getInstance().validateAndLogInAppPurchase(mContext, publicKey, signature, purchaseData, price,
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:750: error: cannot find symbol
        AppsFlyerInAppPurchaseValidatorListener validatorListener = new AppsFlyerInAppPurchaseValidatorListener() {
        ^
  symbol:   class AppsFlyerInAppPurchaseValidatorListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:750: error: cannot find symbol
        AppsFlyerInAppPurchaseValidatorListener validatorListener = new AppsFlyerInAppPurchaseValidatorListener() {
                                                                        ^
  symbol:   class AppsFlyerInAppPurchaseValidatorListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:751: error: method does not override or implement a method from a supertype
            @Override
            ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:759: error: method does not override or implement a method from a supertype
            @Override
            ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:772: error: cannot find symbol
        AppsFlyerLib.getInstance().registerValidatorListener(mContext, validatorListener);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:777: error: cannot find symbol
        AppsFlyerLib.getInstance().setMinTimeBetweenSessions(seconds);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:782: error: cannot find symbol
        result.success(AppsFlyerLib.getInstance().getHostPrefix());
                       ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:786: error: cannot find symbol
        result.success(AppsFlyerLib.getInstance().getSdkVersion());
                       ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:790: error: cannot find symbol
        result.success(AppsFlyerLib.getInstance().getHostName());
                       ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:795: error: cannot find symbol
        AppsFlyerLib.getInstance().setCollectIMEI(isCollect);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:801: error: cannot find symbol
        AppsFlyerLib.getInstance().setCollectAndroidID(isCollect);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:807: error: cannot find symbol
        AppsFlyerLib.getInstance().waitForCustomerUserId(wait);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:813: error: cannot find symbol
        AppsFlyerLib.getInstance().setAdditionalData(customData);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:821: error: package AppsFlyerProperties does not exist
        AppsFlyerProperties.EmailsCryptType cryptType = null;
                           ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:823: error: package AppsFlyerProperties does not exist
            cryptType = AppsFlyerProperties.EmailsCryptType.NONE;
                                           ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:825: error: package AppsFlyerProperties does not exist
            cryptType = AppsFlyerProperties.EmailsCryptType.SHA256;
                                           ^
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:831: error: cannot find symbol
            AppsFlyerLib.getInstance().setUserEmails(cryptType, emails.toArray(new String[0]));
            ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:839: error: cannot find symbol
        AppsFlyerLib.getInstance().setCustomerUserId(userId);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:845: error: cannot find symbol
        AppsFlyerLib.getInstance().setCustomerIdAndLogSession(userId, mContext);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:851: error: cannot find symbol
        AppsFlyerLib.getInstance().setAndroidIdData(androidId);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:857: error: cannot find symbol
        AppsFlyerLib.getInstance().setImeiData(imei);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:863: error: cannot find symbol
        AppsFlyerLib.getInstance().updateServerUninstallToken(mContext, token);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:869: error: cannot find symbol
        AppsFlyerLib.getInstance().stop(isStopped, mContext);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:875: error: cannot find symbol
        AppsFlyerLib.getInstance().setIsUpdate(isUpdate);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:881: error: cannot find symbol
        AppsFlyerLib.getInstance().setCurrencyCode(currencyCode);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:889: error: cannot find symbol
        AppsFlyerLib.getInstance().setHost(hostPrefix, hostName);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:893: error: cannot find symbol
        AppsFlyerConversionListener gcdListener = null;
        ^
  symbol:   class AppsFlyerConversionListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:894: error: cannot find symbol
        DeepLinkListener udlListener = null;
        ^
  symbol:   class DeepLinkListener
  location: class AppsflyerSdkPlugin
/Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java:895: error: cannot find symbol
        AppsFlyerLib instance = AppsFlyerLib.getInstance();
        ^
  symbol:   class AppsFlyerLib
  location: class AppsflyerSdkPlugin
Note: /Users/vagrant/.pub-cache/hosted/pub.dev/appsflyer_sdk-6.15.1/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':appsflyer_sdk:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by olaide-ekolere** [comment]
Hello @sumichell have you found a solution? I am having same issue.

**Comment by sumichell** [comment]
@olaide-ekolere 
Hello, No, I'm still having the problem...

**Comment by sumichell** [comment]
> Hello @sumichell have you found a solution? I am having same issue.
@olaide-ekolere 
Hello, No, I'm still having the problem...

**Comment by olaide-ekolere** [comment]
@sumichell i finally resolved it by upgrading java from `12` to `17`.

**Comment by sumichell** [comment]
> @sumichell i finally resolved it by upgrading java from `12` to `17`.

@olaide-ekolere 

I updated Java to 12 and the problem was solved!
That was very helpful.
Thank you very much.

**Comment by Yonkokilasi** [comment]
I have this same issue and updating my Java did not resolve this
